//Main
npc: npc/dryad/main/buff.txt
npc: npc/dryad/main/jobmaster.txt
npc: npc/dryad/main/platinum_skill.txt
npc: npc/dryad/main/kafra.txt
npc: npc/dryad/main/rental.txt
npc: npc/dryad/main/warper.txt
npc: npc/dryad/main/style.txt
npc: npc/dryad/main/shop.txt
npc: npc/dryad/main/pvp.txt

//Merchant
npc: npc/dryad/merchant/refine.txt

//System
npc: npc/dryad/system/rankstatus.txt

//Guild War
npc: npc/dryad/guildwar/Itemwar.txt
npc: npc/dryad/guildwar/Recall.txt
npc: npc/dryad/guildwar/Warp_guild.txt
npc: npc/dryad/guildwar/guild_config.txt
npc: npc/dryad/guildwar/guild_warp_config.txt
npc: npc/dryad/guildwar/auto_guildwar.txt
npc: npc/dryad/guildwar/warp_guildwar_custom.txt