//Main
npc: npc/dryad/main/buff.txt
npc: npc/dryad/main/jobmaster.txt
npc: npc/dryad/main/platinum_skill.txt
npc: npc/dryad/main/kafra.txt
npc: npc/dryad/main/rental.txt
npc: npc/dryad/main/warper.txt
npc: npc/dryad/main/style.txt
npc: npc/dryad/main/shop.txt
npc: npc/dryad/main/pvp.txt
npc: npc/dryad/main/pvp_party.txt
npc: npc/dryad/main/warp.txt

//Shop
npc: npc/dryad/shop/cashshop.txt
npc: npc/dryad/shop/equiptment.txt
npc: npc/dryad/shop/weapon.txt
npc: npc/dryad/shop/headgear.txt
npc: npc/dryad/shop/card.txt
npc: npc/dryad/shop/bonusshop.txt

//Merchant
npc: npc/dryad/merchant/refine.txt
npc: npc/dryad/merchant/card_remove.txt
npc: npc/dryad/merchant/enchant.txt
npc: npc/dryad/merchant/homunculus.txt
npc: npc/dryad/merchant/pack_elu_ori.txt
npc: npc/dryad/merchant/toolshop.txt

//Quest
npc: npc/dryad/quest/huntingmission.txt

//System
npc: npc/dryad/system/rankstatus.txt
npc: npc/dryad/system/menu.txt
npc: npc/dryad/system/find_monster_cfg.txt
npc: npc/dryad/system/find_monster_sys.txt
npc: npc/dryad/system/clock.txt
npc: npc/dryad/system/vip.txt

//Function
npc: npc/dryad/function/autopot.txt
npc: npc/dryad/function/plagiarize.txt
npc: npc/dryad/function/soulinkerscroll.txt

//Guild War
npc: npc/dryad/guildwar/Itemwar.txt
npc: npc/dryad/guildwar/Recall.txt
npc: npc/dryad/guildwar/Warp_guild.txt
npc: npc/dryad/guildwar/guild_config.txt
npc: npc/dryad/guildwar/guild_warp_config.txt
npc: npc/dryad/guildwar/auto_guildwar.txt
npc: npc/dryad/guildwar/warp_guildwar_custom.txt